### PR TITLE
Run clang-format and check in Travis CI

### PR DESCRIPTION
**Pull request by rshin**

### CODE REVIEW

**Comment by rshin** [comment]
@robertnishihara I think it would be good to apply something similar to Ray. For Python you can use https://github.com/hayd/pep8radius which is equivalent to the git-clang-format script added here and can run autopep8 and yapf (linter and formatter) on only the changed lines (so it's not necessary to go back and fix all the errors found in the existing code).

It would be really cool to automatically push fixes, and add comments to the pull request for the non-automatable errors... but that would be enough work for an entirely separate project.

**Comment by robertnishihara** [comment]
Nice work! Interesting that it prefers `char* s` for variable declarations, but `char *s` in function signatures.

Is this enforcing an 80 character line limit?

**Comment by robertnishihara** [comment]
I introduced a whitespace error to see if Travis would catch it, but it appears to not have caught it. https://github.com/pcmoritz/plasma/compare/temp

**Comment by rshin** [comment]
I think that's an artifact of 
> DerivePointerAlignment (bool)
> If true, analyze the formatted file for the most common alignment of & and \*. PointerAlignment is then used only as fallback.

It should enforce a 80-column limit, but that is also configurable.

I'm not sure why it's failing to catch the whitespace error. The git-clang-format script tries to report errors only on changed lines, and maybe there's a bug in what it compares against for changes.

**Comment by robertnishihara** [comment]
Ooh, that's what the problem was? Good catch.

**Comment by robertnishihara** [comment]
Why make the format script take a commit? Why not just have it operate on whatever is in the local repo?

**Comment by rshin** [comment]
The intent of that is so that the whole repository doesn't need to be reformatted, and the style check is only enforced on new changes. I guess I've done the reformatting anyway, though (except on src/ut*.[ch])

**Comment by robertnishihara** [comment]
I see, either of those are fine with me.

**Comment by pcmoritz** [comment]
This looks really great, +1 for merging! @rshin Can you add your workflow for checking the formatting to the README?

**Pull request merged**
